# -*- coding: utf-8 -*-
"""email.spam.detection.using.nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQV2_16LjtBmNR38I11exN7SYbV9w7rC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import StratifiedGroupKFold, StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

nltk.download('stopwords')

df = pd.read_csv('spam (1).csv',encoding='latin-1')
df.head()

df.shape

df.isnull().sum()

df.info()

df = df[['Category','Message']]
df.columns = ['label','text']

df['label'].value_counts()

sns.countplot(X='label',data = df)
plt.show()

ps = PorterStemmer()
stop_words = stopwords.words('english')

ps
stop_words

def clean_text(text):
  text = text.lower()
  text = re.sub(r'[^\w\s]','',text)
  words = text.split()
  words = [ps.stem(word)for word in words if word not in stop_words]
  return ''.join(words)

df['cleaned_text'] = df['text'].apply(clean_text)

tfidf = TfidfVectorizer(max_features=5000,ngram_range=(1,2))
X = tfidf.fit_transform(df['cleaned_text']).toarray()
y = df['label'].map({'ham':0,'spam':1})

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
for train_index, test_index in skf.split(X,y):
    X_train, X_test = X[train_index],X[test_index]
    y_train, y_test = y[train_index],y[test_index]
    break

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)
print(y_pred)

print("Accuracy:",accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True,fmt='d')
xticklabels=['Ham','Spam'],
yticklabels=['Ham','Spam'],
plt.xlabel("Predicted"),
plt.ylabel("Actual"),
plt.show()

print(classification_report(y_test,y_pred,target_names=['Ham','spam']))

